### PR TITLE
Update cookie policy to v3.6.3

### PR DESCRIPTION
**Pull request by samhotep**
## Done

- Updated the coookie policy to v3.6.3

## QA

- View the demo in an incognito web browser
- **Before** accepting cookies, 
  - Open developer tools and in the console type in `dataLayer`
  - There should be a `{"consent", "default"}` object in the dataLayer
- **After** accepting cookies, 
  - There should be a `{"consent", "update"}` object in the dataLayer

### CODE REVIEW

**Comment by laszlokajtar** [comment]
@samhotep works as intended, the order of the scripts seem fine, values seem fine, however, cookie policy appeared another time after selection

**Review by steverydz — APPROVED** [review]
LGTM 👍

**Comment by samhotep** [comment]
> @samhotep works as intended, the order of the scripts seem fine, values seem fine, however, cookie policy appeared another time after selection

Please try again now

**Comment by laszlokajtar** [comment]
@samhotep lgtm!

**Pull request merged**
